# ====================================================================================================
# Minimal Mistakes 기본 설정
# [참고] https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# ====================================================================================================



# 
# 테마 설정
# ====================================================================================================
minimal_mistakes_skin    : "default"



# 
# 블로그 설정
# ====================================================================================================
locale                   : "ko-KR"
rtl                      : false
title                    : "개구리의 밀실"
title_separator          : "|"
subtitle                 : 
name                     : "Hyeon Wuk Park"
description              : "일상 | 성균관대학교 | 응용AI융합학부 | 파이썬 | Python | 알고리즘 | Algorithm | 인공지능 | AI | Artificial Intelligence | Computer Vision | Notes"
url                      : "https://trail3r.github.io"
baseurl                  : ""
repository               : "trail3r/trail3r.github.io"
teaser                   : 
logo                     : 
masthead_title           : 
breadcrumbs              : false
words_per_minute         : 100
enable_copy_code_button  : false
copyright                : 
copyright_url            : 



# 
# 댓글 설정
# ====================================================================================================
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    strict               : # 1 for enabled, 0 for disabled (default)
    input_position       : # "top", "bottom" # The comment input box will be placed above or below the comments
    emit_metadata        : # 1 for enabled, 0 for disabled (default) # https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#imetadatamessage
    lang                 : # "en" (default)
    lazy                 : # true, false # Loading of the comments will be deferred until the user scrolls near the comments container.
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"



# 
# 보안 설정
# ====================================================================================================
reCaptcha:
  siteKey                :
  secret                 :



# 
# 피드 설정
# ====================================================================================================
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)



# 
# 검색 기능 설정
# ====================================================================================================
search                   : true
search_full_content      : true
search_provider          : lunr

lunr:
  search_within_pages    : # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true



# 
# SEO 검색 엔진 설정
# ====================================================================================================
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :



# 
# SNS 공유 설정
# ====================================================================================================
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles



# 
# 블로그 분석 도구 설정
# ====================================================================================================
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# 
# 프로필 설정
# ====================================================================================================
author:
  name             : "개구리"
  avatar           : "assets/images/minecraft_frog.png"
  bio              : "우물 안 개구리의 일상과 생각 그리고 성장을 그리는 우물 탈출기"
  # location         : "대한민국 (South Korea)"
  # email            :
  links:
    - label: "Gmail"
      icon: "assets/images/links-icon/gmail.svg"
      url: "mailto:gusdnr7223@gmail.com"
    - label: "네이버 블로그"
      icon: "assets/images/links-icon/naver-blog.svg"
      url: "https://blog.naver.com/trail3r"
    - label: "GitHub"
      icon: "assets/images/links-icon/github.svg"
      url: "https://github.com/trail3r"
    - label: "Instagram"
      icon: "assets/images/links-icon/instagram.svg"
      url: "https://instagram.com/trail3r__"



# 
# 푸터 설정
# ====================================================================================================
footer:
  links:
    - label: "네이버 블로그"
      icon: "assets/images/links-icon/naver-blog.svg"
      url: "https://blog.naver.com/trail3r"
    - label: "GitHub"
      icon: "assets/images/links-icon/github.svg"
      url: "https://github.com/trail3r"
    - label: "Instagram"
      icon: "assets/images/links-icon/instagram.svg"
      url: "https://instagram.com/trail3r__"
  since: "2026"



# 
# 파일 인식 설정
# ====================================================================================================
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"



# 
# 파일 변환 설정
# ====================================================================================================
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# 
# 마크다운 설정
# ====================================================================================================
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: tree-sitter
  syntax_highlighter_opts:
    tree_sitter_parsers_dir: "assets/tree_sitter_parsers"
    css_classes: true



# 
# Sass/SCSS 설정
# ====================================================================================================
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



# 
# Outputting 설정
# ====================================================================================================
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones



# 
# jekyll-paginate 설정
# ====================================================================================================
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/



# 
# jekyll-paginate-v2 설정
# [참고] https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
# ====================================================================================================
pagination:
  # Set enabled to true to use paginate v2
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title'  # default: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2


# 
# 플러그인 설정
# ====================================================================================================
plugins:
  # - jekyll-paginate
  - kramdown/syntax_tree_sitter
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  # - jekyll-paginate
  - kramdown/syntax_tree_sitter
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



# 
# 아카이브 설정
# ====================================================================================================
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
# ====================================================================================================
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/



# 
# HTML 압축 설정
# [참고] - https://jch.penibelst.de/
# ====================================================================================================
compress_html:
  clippings: all
  ignore:
    envs: development


# 
# 기본값 설정
# ====================================================================================================
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      active_sidebar: true
      sidebar:
        nav: "sidebar"
      read_time: false
      comments: true
      share: true
      related: false
      toc: true
      toc_sticky: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      active_sidebar: true
      read_time: false
      comments: false
      share: true
      related: false

date_format: "%Y. %m. %d."